- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

- name: restart kibana
  service: name=kibana state=restarted enabled=yes

- name: restart logstash
  service: name=logstash state=restarted enabled=yes

- name: restart apm-server
  service: name=apm-server state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
