---
actions:
  apm:
    action: delete_indices
    description: >-
      Delete indices matching the apm prefix in excess of
      10GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: apm
    - filtertype: space
      disk_space: 10
      use_age: True
      source: creation_date
  metricbeat:
    action: delete_indices
    description: >-
      Delete indices matching the metricbeat prefix in excess of
      10GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: metricbeat
    - filtertype: space
      disk_space: 10
      use_age: True
      source: creation_date
  heartbeat:
    action: delete_indices
    description: >-
      Delete indices matching the heartbeat prefix in excess of
      10GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: heartbeat
    - filtertype: space
      disk_space: 10
      use_age: True
      source: creation_date
  packetbeat:
    action: delete_indices
    description: >-
      Delete indices matching the packetbeat prefix in excess of
      10GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: packetbeat
    - filtertype: space
      disk_space: 10
      use_age: True
      source: creation_date
  logstash:
    action: delete_indices
    description: >-
      Delete indices matching the logstash prefix in excess of
      10GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash
    - filtertype: space
      disk_space: 10
      use_age: True
      source: creation_date
  filebeat:
    action: delete_indices
    description: >-
      Delete indices matching filebeat prefix in excess of
      700GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-7
    - filtertype: space
      disk_space: 640
      use_age: True
      source: creation_date
  filebeat-services:
    action: delete_indices
    description: >-
      Delete indices matching filebeat-services prefix in excess of
      100GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-services-
    - filtertype: space
      disk_space: 100
      use_age: True
      source: creation_date
  filebeat-keycloak:
    action: delete_indices
    description: >-
      Delete indices matching filebeat-keycloak prefix in excess of
      100GB of data, starting with the oldest indices, based on index creation_date.
      An empty index list (from no indices being in excess of the size limit, for
      example) will not generate an error.
    options:
      ignore_empty_list: True
      timeout_override: 300
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-keycloak-
    - filtertype: space
      disk_space: 100
      use_age: True
      source: creation_date
