---
- name: Add zabbix gpg key
  rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

- name: Add zabbix repo
  yum_repository:
    name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: 1
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
    state: present

- name: Clean yum metadata
  command: yum clean all

- name: Install zabbix-agent packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - zabbix-agent
    - zabbix-sender
    - zabbix-get
    - wget
    - nc
    #- redis-tools
