---
- name: Copy addition zabbix configuration file
  copy:
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - zabbix-telegraf.conf
  notify: restart zabbix-agent

- name: Copy telegraf zabbix check script
  copy:
    src: prom2zabbix.py
    dest: /usr/local/bin/prom2zabbix.py
    owner: root
    group: root
    mode: 0755

- name: Reload zabbix before adding template into host
  meta: flush_handlers

- name: Get credentials from Zabbix server
  command: cat /root/.zabbix.creds
  register: credentials
  run_once: true
  delegate_to: "{{ zabbix_server }}"
  check_mode: no    # execute even in dry-run mode

- name: Add telegraf template into host
  delegate_to: "{{ zabbix_server }}"
  command: /root/add_template.py -u "{{ credentials.stdout.split()[0] }}" -p "{{ credentials.stdout.split()[1] }}" -H "{{ inventory_hostname }}" -t "Template-Autodiscovery-Telegraf"
