---
- name: Add external ppa with openjdk 11
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: Add elastic gpg key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elastic repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-oss-7.x
