- name: Install php7.0 necessary packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.0-fpm
    - php7.0
    - php7.0-bcmath
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-gd
    - php7.0-gmp
    - php7.0-intl
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-opcache
    - php7.0-readline
    - php7.0-xml
    - php-igbinary
    - php-imagick
    - php-redis
    - php-geoip
    - composer
    - imagemagick

