---
- name: Add remi repo gpg key
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: Add remi repo
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Clean yum metadata
  command: yum clean all

- name: Install redis packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - redis-tools
    - redis-server

- name: Install NFS server
  yum: name=nfs-kernel-server state=present update_cache=yes
  when: redis_role == "slave"

- name: Install NFS client
  yum: name=nfs-common state=present update_cache=yes
  when: redis_role == "master"
