version: '3'

services:
  mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      ports:
        - 1025:1025
        - 8025:8025
      restart: unless-stopped
      logging:
        driver: json-file
        options:
            max-size: "100m"
            max-file: "5"

networks:
  default:
    external:
      name: ingress-shared
