---
- name: Copy configs
  copy:
    src: configs/
    dest: "{{ vm_compose_dir }}/configs"
  notify:
    - restart victoriametrics
    - restart vmauth
    - restart vmagent
    - restart vmalert

- name: Create compose dir
  file:
    path: "{{ vm_compose_dir }}"
    state: directory

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ vm_compose_dir }}/docker-compose.yml"

- name: Copy systemd unit files
  template:
    src: service.j2
    dest: /lib/systemd/system/{{ item }}.service
  notify:
    - reload systemctl
    - restart {{ item }}
  with_items:
    - victoriametrics
    - vmauth
    - vmagent
    - vmalert

- name: Copy vmauth config
  template:
    src: auth.yml.j2
    dest: "{{ vm_compose_dir }}/configs/auth/auth.yml"
  notify:
    - restart vmauth

- name: Copy vmagent config
  template:
    src: prometheus.yml.j2
    dest: "{{ vm_compose_dir }}/configs/prometheus/prometheus.yml"
  notify:
    - restart vmagent

- name: Copy vmalert config
  template:
    src: alert.yml.j2
    dest: "{{ vm_compose_dir }}/configs/alerts/alert.yml"
  notify:
    - restart vmalert

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ vm_site }}.conf"
  notify:
    - reload nginx

- name: Create symbolic links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    state: link
  with_items:
    - {src: "{{ vm_compose_dir }}", dst: "/etc/victoriametrics"}
    - {src: "{{ vm_data_dir }}/vmdata", dst: "/var/lib/victoriametrics"}
    - {src: "{{ vm_data_dir }}/vmagentdata", dst: "/var/lib/vmagent"}
