---
- name: Add blackfire gpg key
  rpm_key:
    state: present
    key: https://packagecloud.io/gpg.key

- name: Add blackfire repo
  yum_repository:
    name: blackfire
    description: Blackfire PHP Official Repository - $basearch
    baseurl: https://packages.blackfire.io/fedora/blackfire.repo
    gpgcheck: 1
    state: present

- name: Clean yum metadata
  command: yum clean all

- name: Install blackfire packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - blackfire-agent
    - blackfire-php

