- name: Ensure telegraf config contains docker socket
  lineinfile:
    path: "{{ telegraf_config_path }}"
    regexp: "(${HOST_MOUNT_PREFIX})?{{ docker_socket_path }}"
    state: absent
  check_mode: yes
  changed_when: false
  register: docker_already_configured
  tags:
    - configure

- name: Insert docker input into telegraf config
  blockinfile:
    path: "{{ telegraf_config_path }}"
    block: |
      [[inputs.docker]]
        endpoint = "unix://${HOST_MOUNT_PREFIX}{{ docker_socket_path }}"
        source_tag = true
        # for some reasons it doesn't work on this level
        tagexclude = ["annotation.kubernetes*", "*compose_{config*,container*,oneoff*,version*}", "container_{id,version}"]
    marker: "# {mark} ANSIBLE MANAGED BLOCK 'DOCKER AUTODETECT'"
  when: not docker_already_configured.found
  notify: reload telegraf
  tags:
    - configure

- name: Add telegraf into docker if it's available
  shell: usermod -a -G docker telegraf
  ignore_errors: yes
  tags:
    - configure

- name: Check that /etc/default/telegraf exists
  stat:
    path: /etc/default/telegraf
  register: telegraf_default
  tags:
    - configure

- name: Add HOST_MOUNT_PREFIX into /etc/default/telegraf
  lineinfile:
    path: /etc/default/telegraf
    line: HOST_MOUNT_PREFIX=''
  when: telegraf_default.stat.exists
  notify: reload telegraf
  tags:
    - configure
